#+title: Daily work log for Jahnavi Ayyanki

* Month of May
** [2016-05-16 Mon]
   +what is the task i was assigned today?
    we were asked to set up the systems with emacs and git and we were taught how to use git hub repositories.
   + What did I get done against each task?
    we set up our systems accordingly and then we learnt certain commands in git and emacs and implemented them.

** [2016-05-17 Tue]
*** what is the task I was assigned today? 
   we were asked to make a emacs file on various programming languages that we
   will be using and another emacs file on data models and its various
   operations.
  
*** What did I get done against each task?
    I made an emacs file and in which I spoke about various programming
    languages which we are going to use and it also includes a diagram for web
    application development and then I made another emacs folder
    in which I learnt about various data models, entities and their operations.

** [2016-05-18 wed]
*** what is the task I was assigned today?
   We were taught some basic operations of python programming. We were asked to code some operations on python in emacs in group and make a data model file with various operations that we filled in yesterday.

*** What did I get done against each task?
    I made an emacs file with my group members and we coded some of the operations in python and then made various test cases against each operation.
    
** [2016-05-19 wed]
*** what is the task I was assigned today?
    we were told to finish our work on data models and add sessions to it.
    
*** What did I get done against each task?
    we continued our work from yesterday and we added sessions to our models.
    
