#+title: Daily work log for Jahnavi Ayyanki

* Month of May
** [2016-05-16 Mon]
   +what is the task i was assigned today?
    we were asked to set up the systems with emacs and git and we were taught how to use git hub repositories.
   + What did I get done against each task?
    we set up our systems accordingly and then we learnt certain commands in git and emacs and implemented them.

** [2016-05-17 Tue]
*** what is the task I was assigned today? 
   we were asked to make a emacs file on various programming languages that we
   will be using and another emacs file on data models and its various
   operations.
  
*** What did I get done against each task?
    I made an emacs file and in which I spoke about various programming
    languages which we are going to use and it also includes a diagram for web
    application development and then I made another emacs folder
    in which I learnt about various data models, entities and their operations.

** [2016-05-18 wed]
*** what is the task I was assigned today?
   We were taught some basic operations of python programming. We were asked to code some operations on python in emacs in group and make a data model file with various operations that we filled in yesterday.

*** What did I get done against each task?
    I made an emacs file with my group members and we coded some of the operations in python and then made various test cases against each operation.
    
** [2016-05-19 Thurs]
*** what is the task I was assigned today?
    we were told to finish our work on data models and add sessions to it.
    
*** What did I get done against each task?
    we continued our work from yesterday and we added sessions to our models.
    
** [2016-05-20 Fri]
*** what is the task I was assigned today? 
    We were taught about ORM (object relaional model).
    
*** What did I get done against each task?
    we worked on our web application models. we started implenting ORM.

** [2016-05-23 Mon]
*** what is the task I was assigned today? 
    we were taught about MySql and
    databases and how to implement SqlAlchemy in python.
    
*** What did I get done against each task?
    we continued our work on ORM and we implemented MySql in our terminals.
    
** [2016-05-24 Tue]
    Continued the implementation of ORM in the user directory application.
    
** [2016-05-26 Thurs]   
*** what is the task I was assigned today? 
    We learnt about REST API 
    
*** What did I get done against each task?
    We started implementing REST API in the user directory application.
    
** [2016-05-30 Mon]    
   Started working on the front end of the application.
    
** [2016-05-31 Tue] 
   Continued working on the front end part.
   fixed some errors in creating some users in the front end.
    
** [2016-06-1 Wed]     
   Learnt some concepts of Angular JS.
   Continued the implementation of the front end.
   Created some users such as add user, delete user etc.
   
** [2016-06-2 Thurs]   
   Almost done with front end application.
   Faced some errors while implementing.
   started to deploy the whole application using Auto Deployment Services (ADS).
   
** [2016-06-3 Fri]   
   Done with web application development. 
   Couldn't present it because some team members were absent.
    
** [2016-06-6 Mon]     
   Learnt some basic concepts of networking.
   We were taught about IP adress, MAC address and different types of IP adresses.
   Learnt some basic commands in linux o networking such as ssh, sch, rsync, ifconfig.
   
** [2016-06-7 Tue]     
   Installed Open vz and configured it.
   Learnt the differences between containers and virtual machines.
   Learnt some commands in Open VZ.
   Learnt how to create containers and how to do some operations on it.
   We were given an assignment on some commands in Open VZ.
